# Generated by Django 3.1.6 on 2021-02-20 11:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered 10 digits Long.', regex='^\\+?1?\\d{10}$')])),
                ('bank_name', models.CharField(max_length=255)),
                ('account_no', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255, verbose_name='Beneficiary Name')),
                ('mode', models.PositiveIntegerField(choices=[(1, 'IMPS'), (2, 'RTG')])),
                ('ref_no', models.CharField(max_length=255, null=True, verbose_name='Bank Ref No')),
                ('service', models.PositiveIntegerField(choices=[(1, 'MoneyTransfer')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debit_amt', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Debit Amount')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Failure'), (1, 'Success')])),
                ('type', models.PositiveIntegerField(choices=[(0, 'Debit'), (1, 'Credit')])),
                ('remarks', models.TextField(null=True)),
                ('dt', models.DateTimeField(auto_now_add=True, verbose_name='Date & Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
